FROM apache/airflow:3.0.0

RUN pip install --no-cache-dir \
    pandas==2.1.4 \
    scikit-learn==1.5.2 \
    xgboost==2.1.3 \
    joblib==1.4.2 \
    python-dotenv==1.0.1 \
    sqlalchemy==2.0.36 \
    psycopg2-binary==2.9.10 \
    kaggle==1.6.17
